# -*- coding: utf-8 -*-
"""Plotting Categorical Data:: Part 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dte1_tMbz713IQCT8knCt2CFa6jkxVPP

# Plotting with categorical data
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('/content/heart_failure_clinical_records_dataset 2.csv')

data.info()

set(data.dtypes.tolist())

data.hist(figsize=(16, 20), bins=50, xlabelsize=8, ylabelsize=8)

data.corr()['DEATH_EVENT'][:-1]

"""# 1. Categorical scatterplots"""

sns.catplot(x='DEATH_EVENT',y='age',data=data)

sns.catplot(x='DEATH_EVENT',y='age',data=data,jitter=False)

sns.catplot(x='DEATH_EVENT',y='age',data=data,kind='swarm')

sns.catplot(x='DEATH_EVENT',y='age',hue='sex',data=data,kind='swarm')

data.head(10)

sns.catplot(x='smoking',y='age',hue='sex',data=data,kind='swarm')

sns.catplot(x='DEATH_EVENT',y='platelets',hue='sex',data=data,kind='swarm')

sns.catplot(x='high_blood_pressure',y='platelets',hue='sex',data=data,kind='swarm')

sns.catplot(x='high_blood_pressure',y='platelets',hue='diabetes',data=data,kind='swarm')

sns.catplot(x='high_blood_pressure',y='platelets',hue='smoking',data=data,kind='swarm')

x=sns.catplot(x='anaemia',y='platelets',hue='smoking',data=data,kind='swarm')
y=sns.catplot(x='anaemia',y='platelets',hue='sex',data=data,kind='swarm')
z=sns.catplot(x='anaemia',y='platelets',hue='diabetes',data=data,kind='swarm')

"""# 2. Boxplots"""

data.head(5)

cat=['anaemia','diabetes','smoking','sex']
con=['creatinine_phosphokinase','age','ejection_fraction','platelets','serum_creatinine','serum_sodium']
for x in cat:
  for y in con:
      sns.catplot(x='DEATH_EVENT',y=y,hue=x,kind='box',data=data)

cat=['anaemia','diabetes','smoking','sex']
con=['creatinine_phosphokinase','age','ejection_fraction','platelets','serum_creatinine','serum_sodium']
for x in cat:
  for y in con:
      sns.catplot(x='DEATH_EVENT',y=y,hue=x,kind='boxen',data=data)

"""# 3.Violinplots"""

cat=['anaemia','diabetes','smoking','sex']
con=['creatinine_phosphokinase','age','ejection_fraction','platelets','serum_creatinine','serum_sodium']
for x in cat:
  for y in con:
      sns.catplot(x='DEATH_EVENT',y=y,hue=x,kind='violin',data=data)

"""# combine swarmplot() or striplot()"""

cat=['anaemia','diabetes','smoking','sex']
con=['creatinine_phosphokinase','age','ejection_fraction','platelets','serum_creatinine','serum_sodium']
for y in con:
      plot=sns.catplot(x='DEATH_EVENT',y=y,kind='violin',data=data)
      sns.swarmplot(x='DEATH_EVENT',y=y,data=data,color="k", size=3,ax=plot.ax)

"""# 4. Statistical estimation within categories"""

cat=['anaemia','diabetes','smoking','sex']
con=['creatinine_phosphokinase','age','ejection_fraction','platelets','serum_creatinine','serum_sodium']
for x in cat:
  for y in con:
      sns.catplot(x='DEATH_EVENT',y=y,hue=x,kind='bar',data=data)

cat=['anaemia','diabetes','smoking','sex','DEATH_EVENT']
for x in cat:
      sns.catplot(x=x,kind='count',data=data)

"""# 5. Point plots"""

cat=['anaemia','diabetes','smoking','sex']
con=['creatinine_phosphokinase','age','ejection_fraction','platelets','serum_creatinine','serum_sodium']
for x in cat:
  for y in con:
      sns.catplot(x='DEATH_EVENT',y=y,hue=x,kind='point',data=data,markers=["^", "o"], linestyles=["-", "--"],)

